### ISSUE TITLE
Return indices of members

### ISSUE THREAD

**Issue by mikulatomas** [xflr6/bitsets#1]
Hi,

small feature request. Is it possible to implement something like this (performance wise)?

```
from bitsets import bitset

Sample = bitset('Sample', [3,4,5])

sample = Sample.frommembers([3,4])

sample.indices()
```

Expected output of indices:
```
(0, 1)
```

Therefore 3 is on index 0 and 4 is on index 1 in given universum.

Probably similar to `sample.bools()`.

Thanks

**Comment by xflr6** [comment]
Hi Tomáš, how about an iterator?

```python
In [1]: from bitsets import bitset
   ...: 
   ...: Sample = bitset('Sample', (3,4,5))
   ...: 
   ...: sample = Sample.frommembers([3,4])
   ...: 
   ...: list(sample.iter_set())
Out[1]: [0, 1]
```

Current implementation (maybe you spot something to improve): https://github.com/xflr6/bitsets/blob/38678b98e69a9a269fa1ad426e1e4aabf50c9315/bitsets/integers.py#L12-L23

**Comment by mikulatomas** [comment]
Thanks for the fast reply.

I have tried following version, but there was no performance benefit even for large numbers. In fact it was slower.

```python
def indexes(n):
    """Yield index sets unranking n in colexicographical order.

    >>> [tuple(indexes(i)) for i in range(8)]
    [(), (0,), (1,), (0, 1), (2,), (0, 2), (1, 2), (0, 1, 2)]
    """
    i = 0
    while n:
        trailing_zeros = (n ^ (n - 1)).bit_length() - 1

        if trailing_zeros:
            i += trailing_zeros
            n >>= trailing_zeros
        else:
            yield i
            i += 1
            n >>= 1
```

Credits: https://stackoverflow.com/a/63918205/3456664

**Comment by xflr6** [comment]
Thanks. Looks like we only lack documentation for `iter_set`.

**Comment by mikulatomas** [comment]
Agree :) thanks
